"""Adiciona entry_date ao diário

Revision ID: a7ef5a848466
Revises: 86bcf892f938
Create Date: 2025-06-11 13:11:56.405242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7ef5a848466'
down_revision = '86bcf892f938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary_entry', schema=None) as batch_op:
        batch_op.alter_column('entry_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary_entry', schema=None) as batch_op:
        batch_op.alter_column('entry_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
