version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules # Evita sobrescrever node_modules durante build
    ports:
      - "3000:3000"
    # NÃO monte volumes aqui para evitar sobrescrever o node_modules durante build
    depends_on:
      - backend
    command: npm run dev -- --host
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: diario-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: diario
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - backend

volumes:
  mysql_data:
